#!/usr/bin/env bash
set -euo pipefail

# Generate Meta.swift and Schema.swift from JSON specs.
# Usage: Scripts/generate-schema.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMA_DIR="$REPO_ROOT/schema"
OUTPUT_DIR="$REPO_ROOT/Sources/acp-swift-sdk"

# Prefer npx (no global install), fall back to a globally installed quicktype.
if command -v npx >/dev/null 2>&1; then
  QUICKTYPE_CMD=(npx quicktype)
elif command -v quicktype >/dev/null 2>&1; then
  QUICKTYPE_CMD=(quicktype)
else
  echo "quicktype not found. Install with 'npm install -g quicktype' or ensure npx is available." >&2
  exit 1
fi

run_quicktype() {
  local input_json="$1"
  local output_swift="$2"
  local src_lang="${3:-json}"

  if [[ ! -s "$input_json" ]]; then
    echo "Skipping $input_json (missing or empty)." >&2
    return
  fi

  "${QUICKTYPE_CMD[@]}" \
    --lang swift \
    --src "$input_json" \
    --src-lang "$src_lang" \
    --struct-or-class struct \
    --acronym-style original \
    --access-level public \
    --no-initializers \
    --swift-5-support \
    --out "$output_swift"
}

generate_meta_swift() {
  local input_json="$SCHEMA_DIR/meta.json"
  local output_swift="$OUTPUT_DIR/Meta.swift"

  if [[ ! -s "$input_json" ]]; then
    echo "Skipping $input_json (missing or empty)." >&2
    return
  fi

  python3 <<'PY' "${input_json}" "${output_swift}"
import json
import sys
from pathlib import Path

meta_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])

data = json.loads(meta_path.read_text())

def to_camel(name: str) -> str:
    parts = name.split('_')
    return parts[0] + ''.join(p.capitalize() for p in parts[1:]) if parts else ''

agent_methods = data.get("agentMethods", {})
client_methods = data.get("clientMethods", {})
version = data.get("version", 1)

lines = []
lines.append("// This file is generated by Scripts/generate-schema.sh; do not edit manually.\n")
lines.append("import Foundation\n\n")

lines.append("public enum AgentMethod: String {\n")
for key, value in agent_methods.items():
    case_name = to_camel(key)
    lines.append(f"    case {case_name} = \"{value}\"\n")
lines.append("}\n\n")

lines.append("public enum ClientMethod: String {\n")
for key, value in client_methods.items():
    case_name = to_camel(key)
    lines.append(f"    case {case_name} = \"{value}\"\n")
lines.append("}\n\n")

lines.append(f"public let PROTOCOL_VERSION = {version}\n")

out_path.write_text(''.join(lines))
print(f"Generated {out_path}")
PY
}

mkdir -p "$OUTPUT_DIR"

generate_meta_swift
run_quicktype "$SCHEMA_DIR/schema.json" "$OUTPUT_DIR/Schema.swift" schema

echo "Generation complete."
